name: gameshowcase
description: "Game Product Web Project"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.3.0

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  armoyu_services: ^1.0.0+22
  html: ^0.15.5
  video_player: ^2.9.3
  youtube_player_iframe: ^5.2.1
  flutter_inappwebview: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/images/

  uses-material-design: true
